include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    avoid_classes_with_only_static_members: false
    public_member_api_docs: false
    omit_local_variable_types: false
    lines_longer_than_80_chars: false
    discarded_futures: false
    cascade_invocations: false
    avoid_catches_without_on_clauses: false
    avoid_positional_boolean_parameters: false
    prefer_constructors_over_static_methods: false
    use_setters_to_change_properties: false
    no_default_cases: false
    document_ignores: false
    prefer_int_literals: false
    sort_constructors_first: false
    always_put_required_named_parameters_first: false
    always_use_package_imports: false
    avoid_redundant_argument_values: false
    avoid_types_on_closure_parameters: false
    unnecessary_breaks: false
    sort_pub_dependencies: false
    unnecessary_type_name_in_constructor: false
