import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:spatial_draft/core/models/stroke.dart';

/// Pure Dart utility generating standard XML vector SVGs from drawing strokes.
class SvgExportService {
  const SvgExportService._();

  /// Converts a collection of [Stroke]s into an XML SVG document.
  static String exportToSvg({
    required List<Stroke> strokes,
    String title = 'SpatialDraft Vector Export',
    Color? backgroundColor,
    bool fitToContent = true,
    double defaultWidth = 4000.0,
    double defaultHeight = 4000.0,
    double padding = 40.0,
  }) {
    double minX = double.infinity;
    double minY = double.infinity;
    double maxX = -double.infinity;
    double maxY = -double.infinity;

    int totalPoints = 0;
    for (final stroke in strokes) {
      for (final pt in stroke.points) {
        totalPoints++;
        final x = pt.position.dx;
        final y = pt.position.dy;
        if (x < minX) minX = x;
        if (x > maxX) maxX = x;
        if (y < minY) minY = y;
        if (y > maxY) maxY = y;
      }
    }

    double vbX = 0;
    double vbY = 0;
    double vbW = defaultWidth;
    double vbH = defaultHeight;

    if (fitToContent && totalPoints > 0) {
      vbX = math.max(0, minX - padding);
      vbY = math.max(0, minY - padding);
      vbW = (maxX - minX) + (padding * 2);
      vbH = (maxY - minY) + (padding * 2);
      if (vbW < 100) vbW = 100;
      if (vbH < 100) vbH = 100;
    }

    final buffer = StringBuffer();
    buffer.writeln('<?xml version="1.0" encoding="UTF-8" standalone="no"?>');
    buffer.writeln(
      '<svg xmlns="http://www.w3.org/2000/svg" '
      'version="1.1" '
      'viewBox="$vbX $vbY $vbW $vbH" '
      'width="${vbW.toStringAsFixed(1)}" '
      'height="${vbH.toStringAsFixed(1)}">',
    );
    buffer.writeln('  <title>$title</title>');
    buffer.writeln(
      '  <!-- Generated by SpatialDraft - Kinematic Spatial Drafting Studio -->',
    );

    // Optional background rect
    if (backgroundColor != null) {
      final hex = _colorToHex(backgroundColor);
      final opacity = backgroundColor.opacity;
      buffer.writeln(
        '  <rect x="$vbX" y="$vbY" width="$vbW" height="$vbH" '
        'fill="$hex" fill-opacity="$opacity"/>',
      );
    }

    // Group with stroke rendering defaults
    buffer.writeln(
      '  <g fill="none" stroke-linecap="round" stroke-linejoin="round">',
    );

    for (int s = 0; s < strokes.length; s++) {
      final stroke = strokes[s];
      if (stroke.points.isEmpty) continue;

      final hex = _colorToHex(stroke.color);
      final opacity = stroke.color.opacity;
      final width = stroke.lineWeight.baseWidth;
      final isDashed = stroke.lineWeight.isDashed;
      final dashAttr = isDashed ? ' stroke-dasharray="6,4"' : '';

      if (stroke.points.length == 1) {
        final pt = stroke.points.first.position;
        final r = width / 2.0;
        buffer.writeln(
          '    <circle cx="${pt.dx.toStringAsFixed(2)}" '
          'cy="${pt.dy.toStringAsFixed(2)}" '
          'r="${r.toStringAsFixed(2)}" '
          'fill="$hex" fill-opacity="$opacity"/>',
        );
        continue;
      }

      final d = _buildPathData(stroke);
      buffer.writeln(
        '    <path d="$d" stroke="$hex" stroke-width="${width.toStringAsFixed(2)}" '
        'stroke-opacity="$opacity"$dashAttr/>',
      );
    }

    buffer.writeln('  </g>');
    buffer.writeln('</svg>');
    return buffer.toString();
  }

  static String _buildPathData(Stroke stroke) {
    final points = stroke.points;
    final sb = StringBuffer();
    final first = points.first.position;
    sb.write('M ${first.dx.toStringAsFixed(2)} ${first.dy.toStringAsFixed(2)}');

    if (points.length == 2) {
      final p1 = points[1].position;
      sb.write(
        ' L ${p1.dx.toStringAsFixed(2)} ${p1.dy.toStringAsFixed(2)}',
      );
      return sb.toString();
    }

    for (int i = 1; i < points.length - 1; i++) {
      final p0 = points[i].position;
      final p1 = points[i + 1].position;
      final midX = (p0.dx + p1.dx) / 2.0;
      final midY = (p0.dy + p1.dy) / 2.0;
      sb.write(
        ' Q ${p0.dx.toStringAsFixed(2)} ${p0.dy.toStringAsFixed(2)}, '
        '${midX.toStringAsFixed(2)} ${midY.toStringAsFixed(2)}',
      );
    }

    final last = points.last.position;
    sb.write(
      ' L ${last.dx.toStringAsFixed(2)} ${last.dy.toStringAsFixed(2)}',
    );
    return sb.toString();
  }

  static String _colorToHex(Color color) {
    return '#${(color.value & 0x00FFFFFF).toRadixString(16).padLeft(6, '0').toUpperCase()}';
  }
}
